version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      target: development
    volumes:
      - "./:/api"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    build:
      context: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=task-api
      - MYSQL_ROOT_PASSWORD=password
volumes:
  mysql_db:
    driver: local